# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Encryptor do
  before { stub_const('FakeEncryptable', Class.new { include Encryptor }) }

  describe '.generate_encrypted_token' do
    subject(:token) { FakeEncryptable.generate_encrypted_token(uid: 'GP-TEST-0001', secret_key: 'gpm_sk__test') }

    it 'returns a string' do
      expect(token).to be_a(String)
    end

    it 'does not expose raw values in the token' do
      expect(token).not_to include('GP-TEST-0001')
      expect(token).not_to include('gpm_sk__test')
    end
  end

  describe '.decrypt_encrypted_token' do
    subject(:result) { FakeEncryptable.decrypt_encrypted_token(token) }

    context 'with a valid token' do
      let(:token) { FakeEncryptable.generate_encrypted_token(uid: 'GP-TEST-0001', secret_key: 'gpm_sk__test') }

      it 'returns a string-keyed hash with the original values' do
        expect(result).to eq('uid' => 'GP-TEST-0001', 'secret_key' => 'gpm_sk__test')
      end
    end

    context 'with an invalid token' do
      let(:token) { 'invalid_token' }

      it { is_expected.to be_nil }
    end

    context 'with a tampered token' do
      let(:token) { FakeEncryptable.generate_encrypted_token(uid: 'GP-TEST-0001').reverse }

      it { is_expected.to be_nil }
    end
  end

  describe 'purpose isolation' do
    let(:token) { FakeEncryptable.generate_encrypted_token(purpose: :setup, uid: 'GP-TEST-0001') }

    it 'decrypts successfully with the correct purpose' do
      expect(FakeEncryptable.decrypt_encrypted_token(token, purpose: :setup)).to eq('uid' => 'GP-TEST-0001')
    end

    it 'returns nil when decrypted with a different purpose' do
      expect(FakeEncryptable.decrypt_encrypted_token(token, purpose: :other)).to be_nil
    end

    it 'returns nil when decrypted without a purpose' do
      expect(FakeEncryptable.decrypt_encrypted_token(token)).to be_nil
    end
  end

  describe 'cross-model isolation' do
    before { stub_const('OtherEncryptable', Class.new { include Encryptor }) }

    let(:token) { FakeEncryptable.generate_encrypted_token(uid: 'GP-TEST-0001') }

    it 'cannot decrypt a token generated by a different model class' do
      expect(OtherEncryptable.decrypt_encrypted_token(token)).to be_nil
    end
  end
end
