[phases.setup]
aptPkgs = ["libpq-dev", "libvips-dev", "git", "curl", "build-essential"]

[phases.install]
cmds = ["bundle install", "bundle exec bootsnap precompile --gemfile"]

[phases.build]
cmds = ["bundle exec rake assets:precompile", "bundle exec bootsnap precompile app/ lib/"]

[start]
cmd = "bin/start.sh"
